[control_plane]
k8s-control-plane ansible_host=<CONTROL_PLANE_PRIVATE_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/test-kp.pem

[workers]
k8s-worker-1 ansible_host=<WORKER_PRIVATE_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/test-kp.pem

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
